version: "3"

services:
  pinger:
    build: .
    command: python run.py
    restart: always
    ports:
      - 80:5000
    networks:
      - pinger-net
    depends_on:
      - db
  db:
    image: postgres:10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pinger
    networks:
      - pinger-net

networks:
  pinger-net:

volumes:
  postgres_data: