version: "3"

services:
  pinger:
    build: .
    command: python run.py
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - FLASK_ENV=production
      - PING_HOSTS=google.com
      - PING_DELAY_SEC=60
      - PING_FAIL_DELAY_SEC=5
      - DB_URL=postgresql://pinger:pinger@db/pinger
    ports:
      - 80:5000
    networks:
      - pinger-net
    depends_on:
      - db
  db:
    image: postgres:10-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=pinger
      - POSTGRES_PASSWORD=pinger
      - POSTGRES_DB=pinger
    networks:
      - pinger-net

networks:
  pinger-net:

volumes:
  postgres_data: